// Code generated by make registry. DO NOT EDIT.

package plugins

import (
	"errors"

	"github.com/1Password/shell-plugins/plugins/doppler"
	"github.com/1Password/shell-plugins/sdk/schema"
)

var registry = map[string]func() schema.Plugin{
	"doppler": doppler.New,
}

func Get(name string) (schema.Plugin, error) {
	factory, ok := registry[name]
	if !ok {
		return schema.Plugin{}, errors.New("plugin not found")
	}
	return factory(), nil
}

func List() []string {
	names := make([]string, 0, len(registry))
	for name := range registry {
		names = append(names, name)
	}
	return names
}
