package plugins

// This file gets auto-generated by the "make registry" command, so should not be edited by hand.

import (
	"github.com/1Password/shell-plugins/plugins/doppler"
)

func init() {
	Register(doppler.New())
}
